### PR TITLE
Use ladybug geometry instead of rhino geometry for Sunpath center point

### PR DESCRIPTION
**Pull request by Moult**

### CODE REVIEW

**Comment by chriswmackey** [comment]
Hey @Moult . Thanks for catching this and sorry I didn't see this earlier.

[I changed the name of one of the inputs to the Sunpath today](https://github.com/ladybug-tools/ladybug-grasshopper/pull/88) and I included your bug fix here in the PR. So I am closing out this one.

FYI, for future reference, we need both the `.ghuser` objects and the `.py` file to be updated with each PR to the Grasshopper repos and we have created a "LB Export UserObject" component to automate the whole export process from Grasshopper.

Also, if you want to get the updated SunPath component with your fix and my name change, you can run the "LB Versioner" component, which essentially uses pip to update all of your libraries and plugins.  If you're running it on your VPN machine, you'll have to edit [this line of the "LB Versioner" component](https://github.com/ladybug-tools/ladybug-grasshopper/blob/master/ladybug_grasshopper/src/LB%20Versioner.py#L132)

**Comment by Moult** [comment]
Cheers! No worries, is there a way for me to edit the `.ghuser` object without Grasshopper?

By the way, can you check the code again, I see you've lowercased the `z` but kept the variable name the same - I think the variable itself needs to change.

**Comment by chriswmackey** [comment]
Thanks @Moult . Good catch with the variable name. I'll push another fix now.

Unfortunately, `.ghuser` files are binary and cannot be edited without Grasshopper.  If it's going to be an issue and you don't want to use the floating Rhino license that @mostaphaRoudsari mentioned, I can probably just reinterpret all of your PRs on the .py files into ones that also edit the `.ghuser` objects. It just might take me some time each time we do it.

**Comment by chriswmackey** [comment]
I'll also just say that it's really easy to use Rhino's floating licence. It's the most streamlined licence management I've used to date. Of course, if you are on Linux, then there's no good solution here.

**Pull request closed without merging**
